executable = /afs/cern.ch/user/l/leevans/tthbb_legacy_utilities/HTCondor/submit_Feb23_Histograms/bashScripts/dev_config_ttH_STXS1_1l.sh
arguments = $(ClusterId)$(ProcId)
output = output_Feb23_HIstograms/dev_config_ttH_STXS1_1l$(ClusterId)$(ProcId).out
error = /afs/cern.ch/user/l/leevans/tthbb_legacy_utilities/HTCondor
log = /afs/cern.ch/user/l/leevans/tthbb_legacy_utilities/HTCondor/logs/dev_config/dev_config_ttH_STXS1_1l.log
requirements = (OpSysAndVer =?= "CentOS7" ) 
universe = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
+MaxRuntime = 21600
queue